name: google_auth
description: Google Auth plugin for Flutter.
version: 0.0.2
homepage: https://github.com/tranvansang/flutter_google_auth

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.transang.plugins.google_auth
        pluginClass: GoogleAuthPlugin
      ios:
        pluginClass: GoogleAuthPlugin
